changed pacman installation to function, added bootloader install support on demand

diff --git a/usr/share/archboot/installer/setup b/usr/share/archboot/installer/setup
--- a/usr/share/archboot/installer/setup
+++ b/usr/share/archboot/installer/setup
@@ -1946,12 +1946,12 @@ pacman_conf_extra() {
     echo "Server =  ${serverurl}" >> /tmp/pacman.conf
 }
 
-# pacman_conf_grub2()
-# adds grub2 repository for media installation mode
-pacman_conf_grub2() {
+# pacman_conf_bootloader()
+# adds bootloader repository for media installation mode
+pacman_conf_bootloader() {
     local serverurl="${SYNC_URL}"
     # Setup a pacman.conf in /tmp
-    echo "[grub2]" >> /tmp/pacman.conf
+    echo "[bootloader]" >> /tmp/pacman.conf
     echo "Server =  ${serverurl}" >> /tmp/pacman.conf
 }
 
@@ -1966,6 +1966,54 @@ prepare_pacman() {
     DIALOG --infobox "Refreshing package database..." 6 45
     $PACMAN -Sy >$LOG 2>&1 || return 1
     return 0
+}
+
+# Set PACKAGES parameter before running to install wanted packages
+run_pacman(){
+    DIALOG --msgbox "Package installation will begin now.  You can watch the output in the progress window. Please be patient." 0 0
+
+    # create chroot environment on target system
+    # code straight from mkarchroot
+    chroot_mount
+
+    # execute pacman in a subshell so we can follow its progress
+    # pacman output goes /tmp/pacman.log
+    # /tmp/setup-pacman-running acts as a lockfile
+    ( \
+        echo "Installing Packages..." >/tmp/pacman.log ; \
+        echo >>/tmp/pacman.log ; \
+        touch /tmp/setup-pacman-running ; \
+        $PACMAN -S $PACKAGES 2>&1 >> /tmp/pacman.log ; \
+        echo $? > /tmp/.pacman-retcode ; \
+        if [ $(cat /tmp/.pacman-retcode) -ne 0 ]; then
+            echo -e "\nPackage Installation FAILED." >>/tmp/pacman.log
+        else
+            echo -e "\nPackage Installation Complete." >>/tmp/pacman.log
+        fi
+        rm /tmp/setup-pacman-running
+    ) &
+
+    # display pacman output while it's running
+    sleep 2
+    dialog --backtitle "$TITLE" --title " Installing... Please Wait " \
+        --no-kill --tailboxbg "/tmp/pacman.log" 18 70 2>$ANSWER
+    while [ -f /tmp/setup-pacman-running ]; do
+        sleep 1
+    done
+    kill $(cat $ANSWER)
+
+    # pacman finished, display scrollable output
+    local _result=''
+    if [ $(cat /tmp/.pacman-retcode) -ne 0 ]; then
+        _result="Installation Failed (see errors below)"
+    else
+        _result="Installation Complete"
+    fi
+    rm /tmp/.pacman-retcode
+    DIALOG --title "$_result" --exit-label "Continue" \
+        --textbox "/tmp/pacman.log" 18 70 || return 1
+    # ensure the disk is synced
+    sync
 }
 
 # select_packages()
@@ -2103,52 +2151,7 @@ installpkg() {
     if [ "$S_MKFS" != "1" -a "$S_MKFSAUTO" != "1" ]; then
         getdest
     fi
-
-    DIALOG --msgbox "Package installation will begin now.  You can watch the output in the progress window. Please be patient." 0 0
-
-    # create chroot environment on target system
-    # code straight from mkarchroot
-    chroot_mount
-
-    # execute pacman in a subshell so we can follow its progress
-    # pacman output goes /tmp/pacman.log
-    # /tmp/setup-pacman-running acts as a lockfile
-    ( \
-        echo "Installing Packages..." >/tmp/pacman.log ; \
-        echo >>/tmp/pacman.log ; \
-        touch /tmp/setup-pacman-running ; \
-        $PACMAN -S $PACKAGES 2>&1 >> /tmp/pacman.log ; \
-        echo $? > /tmp/.pacman-retcode ; \
-        if [ $(cat /tmp/.pacman-retcode) -ne 0 ]; then
-            echo -e "\nPackage Installation FAILED." >>/tmp/pacman.log
-        else
-            echo -e "\nPackage Installation Complete." >>/tmp/pacman.log
-        fi
-        rm /tmp/setup-pacman-running
-    ) &
-
-    # display pacman output while it's running
-    sleep 2
-    dialog --backtitle "$TITLE" --title " Installing... Please Wait " \
-        --no-kill --tailboxbg "/tmp/pacman.log" 18 70 2>$ANSWER
-    while [ -f /tmp/setup-pacman-running ]; do
-        sleep 1
-    done
-    kill $(cat $ANSWER)
-
-    # pacman finished, display scrollable output
-    local _result=''
-    if [ $(cat /tmp/.pacman-retcode) -ne 0 ]; then
-        _result="Installation Failed (see errors below)"
-    else
-        _result="Installation Complete"
-    fi
-    rm /tmp/.pacman-retcode
-    DIALOG --title "$_result" --exit-label "Continue" \
-        --textbox "/tmp/pacman.log" 18 70 || return 1
-    # ensure the disk is synced
-    sync
-
+    run_pacman
     S_INSTALL=1
     NEXTITEM="6"
     # automagic time!
@@ -2406,9 +2409,20 @@ dosyslinux() {
     getrootfs
     getraidarrays
     getcryptsetup
-    if [ ! -e /usr/bin/syslinux ]; then
-        DIALOG --msgbox "Error: Couldn't find syslinux binary. Is SYSLINUX installed?" 0 0
-        return 1
+    if [ ! -e $DESTDIR/usr/bin/syslinux ]; then
+        DIALOG --msgbox "Couldn't find syslinux binary, installing syslinux now ..." 0 0
+        ### HACK!
+        # syslinux is not part of core repository
+        if [ "$MODE" = "ftp" ]; then
+            pacman_conf_extra
+        else
+            pacman_conf_bootloader
+        fi
+        PACKAGES="syslinux"
+        prepare_pacman
+        run_pacman
+        # reset PACKAGES after installing
+        PACKAGES=""
     fi
     DIALOG --msgbox "Attention:\nIn order to get a booting system, you need the boot flag on the partition syslinux will boot the kernel from!" 0 0
     # look for a separately-mounted /boot partition
@@ -2433,7 +2447,7 @@ dosyslinux() {
     ROOTDEV=$(cat $ANSWER)
     # generate syslinux.cfg
     TEMPDIR=/tmp
-    MBR=/usr/lib/syslinux/mbr.bin
+    MBR=$DESTDIR/usr/lib/syslinux/mbr.bin
     [ -e ${TEMPDIR}/syslinux.cfg ] && rm ${TEMPDIR}/syslinux.cfg
     echo "prompt 1" >> ${TEMPDIR}/syslinux.cfg
     echo "timeout 300" >> ${TEMPDIR}/syslinux.cfg
@@ -2476,8 +2490,9 @@ dosyslinux() {
     cp  ${TEMPDIR}/boot.msg ${DESTDIR}/boot/boot.msg
     cat ${MBR} > ${ROOTDEV}
     [ -e ${DESTDIR}/boot/ldlinux.sys ] && rm  ${DESTDIR}/boot/ldlinux.sys
-    syslinux $bootdev >$LOG 2>&1
+    $DESTDIR/usr/bin/syslinux $bootdev >$LOG 2>&1
     if [ $? -gt 0 ]; then
+        chroot_umount
         DIALOG --msgbox "Error installing SYSLINUX. (see $LOG for output)" 0 0
         return 1
     fi
@@ -2489,8 +2504,12 @@ dolilo() {
     getraidarrays
     getcryptsetup
     if [ ! -f $DESTDIR/etc/lilo.conf ]; then
-        DIALOG --msgbox "Error: Couldn't find $DESTDIR/etc/lilo.conf. Is LILO installed?" 0 0
-        return 1
+        DIALOG --msgbox "Couldn't find $DESTDIR/etc/lilo.conf, installing lilo now ..." 0 0
+        prepare_pacman
+        PACKAGES="lilo"
+        run_pacman
+        # reset PACKAGES after installing
+        PACKAGES=""
     fi
     # Try to auto-configure LILO...
     if ! [ "$PART_ROOT" = "" -a "$S_LILO" = "1" ]; then
@@ -2547,8 +2566,12 @@ dogrub() {
     FAIL_RAID=""
     FAIL_DM=""
     if [ ! -f $DESTDIR/boot/grub/menu.lst ]; then
-        DIALOG --msgbox "Error: Couldn't find $DESTDIR/boot/grub/menu.lst. Is GRUB installed?" 0 0
-        return 1
+        DIALOG --msgbox "Couldn't find $DESTDIR/boot/grub/menu.lst, installing grub now ..." 0 0
+        prepare_pacman
+        PACKAGES="grub"
+        run_pacman
+        # reset PACKAGES after installing
+        PACKAGES=""
     fi
     if ! [ "$(dmraid -r | grep ^no )" ]; then
         USE_DMRAID=""
@@ -2778,19 +2801,20 @@ EOF
 }
 
 dogrub2(){
-    ### HACK!
-    # grub2 is not part of core repository and conflicts with grub -> uninstall grub first!
-    if [ "$MODE" = "ftp" ]; then
-        pacman_conf_extra
-    else
-        pacman_conf_grub2
-    fi
-    prepare_pacman
-    DIALOG --infobox "Installing grub2 package..." 0 0
-    $PACMAN -S grub2  2>&1 >> /tmp/pacman.log
     if [ ! -f $DESTDIR/boot/grub/grub.cfg ]; then
-        DIALOG --msgbox "Error: Couldn't find $DESTDIR/boot/grub/grub.cfg Is GRUB2 installed?" 0 0
-        return 1
+        DIALOG --msgbox "Couldn't find $DESTDIR/boot/grub/grub.cfg, installing grub2 now ..." 0 0
+        ### HACK!
+        # grub2 is not part of core repository and conflicts with grub -> uninstall grub first!
+        if [ "$MODE" = "ftp" ]; then
+            pacman_conf_extra
+        else
+            pacman_conf_bootloader
+        fi
+        prepare_pacman
+        PACKAGES="grub2"
+        run_pacman
+        # reset PACKAGES after installing
+        PACKAGES=""
     fi
 }
 
