start adding btrfs raid support

diff --git a/usr/share/archboot/installer/setup b/usr/share/archboot/installer/setup
--- a/usr/share/archboot/installer/setup
+++ b/usr/share/archboot/installer/setup
@@ -755,104 +755,6 @@ set_guid () {
     DIALOG --defaultno --yesno "Do you want to use GUID Partition Table (GPT)?\n\nIt is a standard for the layout of the partition table on a physical hard disk. Although it forms a part of the Extensible Firmware Interface (EFI) standard (Intel's proposed replacement for the PC BIOS), it is also used on some BIOS systems because of the limitations of MBR partition tables, which restrict maximum disk size to 2 TiB.\n\nWindows XP and earlier Windows systems cannot (without hacks) read or write to drives formatted with a GUID partition table, however, Vista and Windows 7 and later versions include this capability.\n\nAttention:\n- Please check if your other operating systems have GPT support!\n- Use this option for a GRUB2 setup, which should support LVM, RAID etc.,\n  which doesn't fit into the usual 30k MS-DOS MBR gap." 0 0 && GUIDPARAMETER=yes
 }
 
-# _mkfs()
-# Create and mount filesystems in our destination system directory.
-#
-# args:
-#  domk: Whether to make the filesystem or use what is already there
-#  device: Device filesystem is on
-#  fstype: type of filesystem located at the device (or what to create)
-#  dest: Mounting location for the destination system
-#  mountpoint: Mount point inside the destination system, e.g. '/boot'
-
-# returns: 1 on failure
-_mkfs() {
-    local _domk=$1
-    local _device=$2
-    local _fstype=$3
-    local _dest=$4
-    local _mountpoint=$5
-    local _labelname=$6
-    local _fsoptions=$7
-
-    # we have two main cases: "swap" and everything else.
-    if [ "${_fstype}" = "swap" ]; then
-        swapoff ${_device} >/dev/null 2>&1
-        if [ "${_domk}" = "yes" ]; then
-            mkswap -L ${_labelname} ${_device} >$LOG 2>&1
-            if [ $? != 0 ]; then
-                DIALOG --msgbox "Error creating swap: mkswap ${_device}" 0 0
-                return 1
-            fi
-        fi
-        swapon ${_device} >$LOG 2>&1
-        if [ $? != 0 ]; then
-            DIALOG --msgbox "Error activating swap: swapon ${_device}" 0 0
-            return 1
-        fi
-    else
-        # make sure the fstype is one we can handle
-        local knownfs=0
-        for fs in xfs jfs reiserfs ext2 ext3 ext4 btrfs ntfs-3g vfat; do
-            [ "${_fstype}" = "${fs}" ] && knownfs=1 && break
-        done
-        if [ $knownfs -eq 0 ]; then
-            DIALOG --msgbox "unknown fstype ${_fstype} for ${_device}" 0 0
-            return 1
-        fi
-        # if we were tasked to create the filesystem, do so
-        if [ "${_domk}" = "yes" ]; then
-            local ret
-            case ${_fstype} in
-                xfs)      mkfs.xfs ${_fsoptions} -L ${_labelname} -f ${_device} >$LOG 2>&1; ret=$? ;;
-                jfs)      yes | mkfs.jfs ${_fsoptions} -L ${_labelname} ${_device} >$LOG 2>&1; ret=$? ;;
-                reiserfs) yes | mkreiserfs ${_fsoptions} -l ${_labelname} ${_device} >$LOG 2>&1; ret=$? ;;
-                ext2)     mkfs.ext2 -L ${_fsoptions} ${_labelname} ${_device} >$LOG 2>&1; ret=$? ;;
-                ext3)     mke2fs ${_fsoptions} -L ${_labelname} -t ext3 ${_device} >$LOG 2>&1; ret=$? ;;
-                ext4)     mke2fs ${_fsoptions} -L ${_labelname} -t ext4 ${_device} >$LOG 2>&1; ret=$? ;;
-                btrfs)    mkfs.btrfs ${_fsoptions} -L ${_labelname} ${_device} >$LOG 2>&1; ret=$? ;;
-                ntfs-3g)  mkfs.ntfs ${_fsoptions} -L ${_labelname} ${_device} >$LOG 2>&1; ret=$? ;;
-                vfat)     mkfs.vfat ${_fsoptions} -n ${_labelname} ${_device} >$LOG 2>&1; ret=$? ;;
-                # don't handle anything else here, we will error later
-            esac
-            if [ $ret != 0 ]; then
-                DIALOG --msgbox "Error creating filesystem ${_fstype} on ${_device}" 0 0
-                return 1
-            fi
-            sleep 2
-        fi
-        # create our mount directory
-        mkdir -p ${_dest}${_mountpoint}
-        # mount the bad boy
-        mount -t ${_fstype} ${_device} ${_dest}${_mountpoint} >$LOG 2>&1
-        if [ $? != 0 ]; then
-            DIALOG --msgbox "Error mounting ${_dest}${_mountpoint}" 0 0
-            return 1
-        fi
-    fi
-
-    # add to .device-names for config files
-    local _uuid="$(getuuid ${_device})"
-    local _label="$(getlabel ${_device})"
-    echo "# DEVICE DETAILS: ${_device} UUID=$_uuid LABEL=$_label" >> /tmp/.device-names
-    # add to temp fstab
-    if [ "$NAME_SCHEME_PARAMETER" = "UUID" ]; then
-        if [ -n "${_uuid}" ]; then
-            _device="UUID=${_uuid}"
-        fi
-    elif [ "$NAME_SCHEME_PARAMETER" = "LABEL" ]; then
-        if [ -n "${_label}" ]; then
-            _device="LABEL=${_label}"
-        fi
-    fi
-    echo -n "${_device} ${_mountpoint} ${_fstype} defaults 0 " >>/tmp/.fstab
-    if [ "${_fstype}" = "swap" ]; then
-        echo "0" >>/tmp/.fstab
-    else
-        echo "1" >>/tmp/.fstab
-    fi
-}
-
 # Get a list of available disks for use in the "Available disks" dialogs. This
 # will print the mountpoints as follows, getting size info from /sys:
 #   /dev/sda: 64000 MB
@@ -1971,6 +1873,81 @@ partition() {
     S_PART=1
 }
 
+select_btrfs_raid_devices () {
+    # show all devices with sizes
+    # DIALOG --msgbox "DISKS:\n$(_getavaildisks)\n\nPARTITIONS:\n$(_getavailpartitions)" 0 0
+    # select the second device to use, no missing option available!
+    RAIDNUMBER=2
+    DIALOG --menu "Select device $RAIDNUMBER" 21 50 13 $PARTS 2>$ANSWER || return 1
+    PART=$(cat $ANSWER)
+    echo "$PART" >>/tmp/.btrfs-raid
+    while [ "$PART" != "DONE" ]; do
+        BTRFS_DONE=""
+        RAIDNUMBER=$(($RAIDNUMBER + 1))
+        # RAID10 need 4 devices!
+        [ "$RAIDNUMBER" -ge 3 -a ! "$BTRFS_LEVEL" = "RAID10" ] && BTRFS_DONE="DONE _"
+        [ "$RAIDNUMBER" -ge 5 -a "$BTRFS_LEVEL" = "RAID10" ] && BTRFS_DONE="DONE _"
+        # clean loop from used partition and options
+        PARTS="$(echo $PARTS | sed -e "s#${PART}\ _##g")"
+        # add more devices
+        DIALOG --menu "Select additional device $RAIDNUMBER" 21 50 13 $PARTS $BTRFS_DONE 2>$ANSWER || return 1
+        PART=$(cat $ANSWER)
+        [ "$PART" = "DONE" ] && break
+        echo "$PART" >>/tmp/.btrfs-raid
+     done
+     # final step ask if everything is ok?
+     DIALOG --yesno "Would you like to create $BTRFS_DEVICE like this?\n\nLEVEL:\n$BTRFS_LEVEL\n\nDEVICES:\n$(for i in $(cat /tmp/.btrfs-raid); do echo "$i\n";done)" 0 0 && BTRFS_RAID_FINISH="DONE"
+     BTRFS_RAID_DEVICES=""
+     if [ -n /tmp/.btrfs-raid ]; then
+         for i in $(cat /tmp/.btrfs-raid); do
+             BTRFS_RAID_DEVICES="$BTRFS_RAID_DEVICES $i"
+         done
+     fi
+}
+
+btrfs_raid_level() {
+    BTRFS_RAIDLEVELS="NONE - RAID0 - RAID1 - RAID10 - SINGLE -"
+    BTRFS_RAID_FINISH=""
+    BTRFS_LEVEL=""
+    BTRFS_DEVICE="$PART"
+    : >/tmp/.btrfs-raid
+    DIALOG --msgbox "BTRFS RAID OPTIONS:\n\nBTRFS has options to control the raid configuration for data and metadata.\nValid choices are RAID0, RAID1, RAID10 and single.\nSINGLE means that no duplication of metadata is done, which may be desired when using hardware raid. 
+RAID10 requires at least 4 devices.\n\nIf you don't need this feature select NONE." 0 0
+    while [ "$BTRFS_RAID_FINISH" != "DONE" ]; do
+        DIALOG --menu "Select the raid level you want to use" 21 50 13 $BTRFS_RAIDLEVELS 2>$ANSWER || return 1
+        BTRFS_LEVEL=$(cat $ANSWER)
+        [ "$BTRFS_LEVEL" = "NONE" ] && break
+        # take selected device as 1st device, add additional devices in part below.
+        select_btrfs_raid_devices
+    done
+}
+
+# find btrfs subvolume
+find_btrfs_subvolume(){
+    btrfs device scan
+    BTRFSMP="$(mktemp -d /tmp/brtfsmp.XXXX)"
+    mount $PART $BTRFSMP
+    for i in $(btrfs subvolume list $BTRFSMP | cut -d " " -f 7); do
+        echo $i
+    done
+    umount $BTRFSMP
+    rm -r $BTRFSMP
+}
+
+choose_btrfs_subvolume () {
+ echo "dummy function"
+}
+
+create_btrfs_subvolume() {
+  echo "dummy function"
+}
+
+prepare_btrfs() {
+    btrfs_raid_level
+    #create_btrfs_subvolume
+    #btrfs_compress
+}
+
 select_filesystem() {
     RUN_CREATE_FILESYSTEM=""
     DIALOG --menu "Select a filesystem for $PART" 21 50 13 $FSOPTS 2>$ANSWER || return 1
@@ -1988,6 +1965,131 @@ enter_mountpoint() {
             MP=""
         fi
     done
+}
+
+create_filesystem() {
+    LABEL_NAME=""
+    RUN_CREATE_FILESYSTEM=""
+    DIALOG --yesno "Would you like to create a filesystem on $PART?\n\n(This will overwrite existing data!)" 0 0 && DOMKFS="yes"
+    if [ "$DOMKFS" = "yes" ]; then
+        while [ "${LABEL_NAME}" = "" ]; do
+            DIALOG --inputbox "Enter the LABEL name for the device, keep it short\n(not more than 12 characters) and use no spaces or special\ncharacters." 10 65 \
+            "$(blkid -c=/dev/null -o value -s LABEL $PART)" 2>$ANSWER || return 1
+            LABEL_NAME=$(cat $ANSWER)
+            if grep ":$LABEL_NAME$" /tmp/.parts; then
+                DIALOG --msgbox "ERROR: You have defined 2 identical LABEL names! Please enter another name." 8 65
+                LABEL_NAME=""
+            fi
+        done
+        if [ "$FSTYPE" = "btrfs" ]; then
+            prepare_btrfs
+        fi
+        DIALOG --inputbox "Enter additional options to the filesystem creation utility.\nUse this field only, if the defaults are not matching your needs,\nelse just leave it empty." 10 70  2>$ANSWER || return 1
+        FS_OPTIONS=$(cat $ANSWER)
+    else
+        if [ "$FSTYPE" = "btrfs" ]; then
+            choose_btrfs_subvolume
+        fi
+    fi
+    RUN_CREATE_FILESYSTEM="yes"
+}
+
+# _mkfs()
+# Create and mount filesystems in our destination system directory.
+#
+# args:
+#  domk: Whether to make the filesystem or use what is already there
+#  device: Device filesystem is on
+#  fstype: type of filesystem located at the device (or what to create)
+#  dest: Mounting location for the destination system
+#  mountpoint: Mount point inside the destination system, e.g. '/boot'
+
+# returns: 1 on failure
+_mkfs() {
+    local _domk=$1
+    local _device=$2
+    local _fstype=$3
+    local _dest=$4
+    local _mountpoint=$5
+    local _labelname=$6
+    local _fsoptions=$7
+
+    # we have two main cases: "swap" and everything else.
+    if [ "${_fstype}" = "swap" ]; then
+        swapoff ${_device} >/dev/null 2>&1
+        if [ "${_domk}" = "yes" ]; then
+            mkswap -L ${_labelname} ${_device} >$LOG 2>&1
+            if [ $? != 0 ]; then
+                DIALOG --msgbox "Error creating swap: mkswap ${_device}" 0 0
+                return 1
+            fi
+        fi
+        swapon ${_device} >$LOG 2>&1
+        if [ $? != 0 ]; then
+            DIALOG --msgbox "Error activating swap: swapon ${_device}" 0 0
+            return 1
+        fi
+    else
+        # make sure the fstype is one we can handle
+        local knownfs=0
+        for fs in xfs jfs reiserfs ext2 ext3 ext4 btrfs ntfs-3g vfat; do
+            [ "${_fstype}" = "${fs}" ] && knownfs=1 && break
+        done
+        if [ $knownfs -eq 0 ]; then
+            DIALOG --msgbox "unknown fstype ${_fstype} for ${_device}" 0 0
+            return 1
+        fi
+        # if we were tasked to create the filesystem, do so
+        if [ "${_domk}" = "yes" ]; then
+            local ret
+            case ${_fstype} in
+                xfs)      mkfs.xfs ${_fsoptions} -L ${_labelname} -f ${_device} >$LOG 2>&1; ret=$? ;;
+                jfs)      yes | mkfs.jfs ${_fsoptions} -L ${_labelname} ${_device} >$LOG 2>&1; ret=$? ;;
+                reiserfs) yes | mkreiserfs ${_fsoptions} -l ${_labelname} ${_device} >$LOG 2>&1; ret=$? ;;
+                ext2)     mkfs.ext2 -L ${_fsoptions} ${_labelname} ${_device} >$LOG 2>&1; ret=$? ;;
+                ext3)     mke2fs ${_fsoptions} -L ${_labelname} -t ext3 ${_device} >$LOG 2>&1; ret=$? ;;
+                ext4)     mke2fs ${_fsoptions} -L ${_labelname} -t ext4 ${_device} >$LOG 2>&1; ret=$? ;;
+                btrfs)    mkfs.btrfs ${_fsoptions} -L ${_labelname} ${_device} >$LOG 2>&1; ret=$? ;;
+                ntfs-3g)  mkfs.ntfs ${_fsoptions} -L ${_labelname} ${_device} >$LOG 2>&1; ret=$? ;;
+                vfat)     mkfs.vfat ${_fsoptions} -n ${_labelname} ${_device} >$LOG 2>&1; ret=$? ;;
+                # don't handle anything else here, we will error later
+            esac
+            if [ $ret != 0 ]; then
+                DIALOG --msgbox "Error creating filesystem ${_fstype} on ${_device}" 0 0
+                return 1
+            fi
+            sleep 2
+        fi
+        # create our mount directory
+        mkdir -p ${_dest}${_mountpoint}
+        # mount the bad boy
+        mount -t ${_fstype} ${_device} ${_dest}${_mountpoint} >$LOG 2>&1
+        if [ $? != 0 ]; then
+            DIALOG --msgbox "Error mounting ${_dest}${_mountpoint}" 0 0
+            return 1
+        fi
+    fi
+
+    # add to .device-names for config files
+    local _uuid="$(getuuid ${_device})"
+    local _label="$(getlabel ${_device})"
+    echo "# DEVICE DETAILS: ${_device} UUID=$_uuid LABEL=$_label" >> /tmp/.device-names
+    # add to temp fstab
+    if [ "$NAME_SCHEME_PARAMETER" = "UUID" ]; then
+        if [ -n "${_uuid}" ]; then
+            _device="UUID=${_uuid}"
+        fi
+    elif [ "$NAME_SCHEME_PARAMETER" = "LABEL" ]; then
+        if [ -n "${_label}" ]; then
+            _device="LABEL=${_label}"
+        fi
+    fi
+    echo -n "${_device} ${_mountpoint} ${_fstype} defaults 0 " >>/tmp/.fstab
+    if [ "${_fstype}" = "swap" ]; then
+        echo "0" >>/tmp/.fstab
+    else
+        echo "1" >>/tmp/.fstab
+    fi
 }
 
 mountpoints() {
@@ -2048,7 +2150,7 @@ mountpoints() {
             fi
             [ "$RUN_CREATE_FILESYSTEM" = "yes" ] && DO_ROOT=DONE
         done
-        echo "$PART:$FSTYPE:/:$DOMKFS:$LABEL_NAME:$FS_OPTIONS" >>/tmp/.parts
+        echo "$PART:$FSTYPE:/:$DOMKFS:$LABEL_NAME:$FS_OPTIONS:$BTRFS_LEVEL:$BTRFS_SUBVOLUME" >>/tmp/.parts
         PARTS="$(echo $PARTS | sed -e "s#${PART}\ _##g")"
         #
         # Additional partitions
@@ -2074,7 +2176,7 @@ mountpoints() {
                 [ "$RUN_CREATE_FILESYSTEM" = "yes" ] && DO_ADDITIONAL="DONE"
             done
             if [ "$PART" != "DONE" ]; then
-                echo "$PART:$FSTYPE:$MP:$DOMKFS:$LABEL_NAME:$FS_OPTIONS" >>/tmp/.parts
+                echo "$PART:$FSTYPE:$MP:$DOMKFS:$LABEL_NAME:$FS_OPTIONS:$BTRFS_LEVEL:$BTRFS_SUBVOLUME" >>/tmp/.parts
                 PARTS="$(echo $PARTS | sed -e "s#${PART}\ _##g")"
             fi
         done
@@ -2665,25 +2767,6 @@ getrootlabel() {
     fi
 }
 
-create_filesystem() {
-    LABEL_NAME=""
-    RUN_CREATE_FILESYSTEM=""
-    DIALOG --yesno "Would you like to create a filesystem on $PART?\n\n(This will overwrite existing data!)" 0 0 && DOMKFS="yes"
-    if [ "$DOMKFS" = "yes" ]; then
-        while [ "${LABEL_NAME}" = "" ]; do
-            DIALOG --inputbox "Enter the LABEL name for the device, keep it short\n(not more than 12 characters) and use no spaces or special\ncharacters." 10 65 \
-            "$(blkid -c=/dev/null -o value -s LABEL $PART)" 2>$ANSWER || return 1
-            LABEL_NAME=$(cat $ANSWER)
-            if grep ":$LABEL_NAME$" /tmp/.parts; then
-                DIALOG --msgbox "ERROR: You have defined 2 identical LABEL names! Please enter another name." 8 65
-                LABEL_NAME=""
-            fi
-        done
-        DIALOG --inputbox "Enter additional options to the filesystem creation utility.\nUse this field only, if the defaults are not matching your needs,\nelse just leave it empty." 10 70  2>$ANSWER || return 1
-        FS_OPTIONS=$(cat $ANSWER)
-    fi
-    RUN_CREATE_FILESYSTEM="yes"
-}
 
 # basic checks needed for all bootloaders
 common_bootloader_checks() {
